# Generated by Django 5.1.7 on 2025-03-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='skug',
            new_name='slug',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
