# Generated by Django 5.1.7 on 2025-04-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_сategory_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
